projects:
  app:
    schemaPath: apollo-server/schema.graphql
    includes:
      - '**/*.gql'
      - '**/*.graphql'
    extensions:
      endpoints:
        default: 'http://localhost:4006/graphql'
